[project]
name = "alts-modules"
dynamic = ["version"]
license = { text = "MIT" }
description = "Some common modules for the ALTS"
authors = [
    {name = "bela127", email="bhb127@outlook.de"}
]
maintainers = [
    {name = "Benjamin Gors", email="benjamin.gorskis@gmail.com"}
]
requires-python = ">=3.9,<3.10"
dependencies = [
    "alts-core @ git+https://github.com/bela127/alts-core.git@dev",
    "nptyping >=2.0.0a1",
    "matplotlib (>=3.6.3,<4.0.0)",
    "scikit-learn (>=1.2.0,<2.0.0)",
    "paramz @ git+https://github.com/bela127/paramz.git",
    "GPy @ git+https://github.com/SheffieldML/GPy.git"
]

[tool.poetry]
version = "0.6.0"
#packages = [
#    { include = "alts/modules", from = "." }
#]

[poetry.group.dev.dependencies]
pytest = "^6.2.5"
mypy = "^0.910"
black = "^21.6b0"
flake8 = "^4.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[mypy]
plugins = "numpy.typing.mypy_plugin"

