# This workflow will install Python dependencies and run tests with a single version of Python
name: Unit Tests on version 3.9.6

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - 3.9.6
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        sudo apt update
        sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev wget curl llvm \
        libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git
    - name: Install python version via pyenv
      uses: gabrielfalcao/pyenv-action@v17
      with:
        default: "${{ matrix.python }}"
        command: pip install -U pip  # upgrade pip after installing python
    - name: Install poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo '#Adding Poetry to path' >> ~/.bashrc
        echo 'export PATH="~/.local/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        poetry config virtualenvs.prefer-active-python true
        poetry config virtualenvs.in-project true
        poetry env use 3.9.6
    - name: Setup virtual environment with poetry
      run: |
        cd alts-modules
        poetry install
        source ./.venv/bin/activate
    - name: Test with pytest
      run: |
        pytest