# This workflow will install Python dependencies and run tests with a single version of Python
name: Unit Tests on version 3.9.6

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pytest
        sudo apt update
        sudo apt install -y make build-essential libssl-dev zlib1g-dev libbz2-dev \
        libreadline-dev libsqlite3-dev wget curl llvm \
        libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python3-openssl git
    - name: Install pyenv
      run: |
        curl -L https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer | bash
        echo '#Adding Pyenv to path' >> ~/.bashrc
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.bashrc
        echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.bashrc
        echo 'eval "$(pyenv init -)"' >> ~/.bashrc
        echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
        echo 'command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.profile
        echo 'eval "$(pyenv init -)"' >> ~/.profile
        source ~/.bashrc
    - name: Setup pyenv
      run: |
        pyenv install 3.9.6
        curl -sSL https://install.python-poetry.org | python3 -
        echo '#Adding Poetry to path' >> ~/.bashrc
        echo 'export PATH="home/user/.local/bin:$PATH"' >> ~/.bashrc
        source ~/.bashrc
        poetry config virtualenvs.prefer-active-python true
        poetry config virtualenvs.in-project true
    - name: Setup virtual environment with poetry
      run: |
        poetry install
    - name: Test with pytest
      run: |
        pytest