# This workflow will install Python dependencies and run tests with a single version of Python
name: Unit Tests

on:
  push:
    branches: [ "dev", "main" ]
  pull_request:
    branches: [ "dev", "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      image: chicken
      options: --user root
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        pip install poetry
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Setup virtual environment
      run: |
        

    - name: Test with pytest
      run: |
        pytest